import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { plusJakarta } from "@/public/font";

export const metadata: Metadata = {
  title: "Ynsect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        <AuthProvider>
          <>{children}</>
        </AuthProvider>
      </body>
    </html>
  );
}
